### PR TITLE
Patch to error on line 1 at column 7: pom.xml

### PR DESCRIPTION
**Pull request by Darker935**
Fixing unnecessary xml tag, that's causing error when building

### CODE REVIEW

**Comment by Darker935** [comment]
> Does it compile for Android now though?

I've did it wrong, sorry. I'm having to do the commits directly through github, as my project is not installing the necessary dependencies to build locally and test

image

**Comment by Darker935** [comment]
But this error is fixed now

image

**Comment by KanzakiisYU** [comment]
> But this error is fixed now
> 
> image

error bro
image


my 

> build.gradle
```
plugins {
    id 'com.android.application'
}



android {
    namespace 'com.konjousoft.whatsappbot'
    compileSdk 34

    defaultConfig {
        applicationId "com.konjousoft.whatsappbot"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}




dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.github.auties00:cobalt:0.0.5'
    implementation "androidx.multidex:multidex:2.0.1"
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    annotationProcessor 'com.github.auties00:cobalt:0.0.5'

}
```

**Comment by Darker935** [comment]
> > But this error is fixed now
> error bro

It's not fixed yet lmao

**Comment by KanzakiisYU** [comment]
> > > But this error is fixed now
> > > error bro
> 
> It's not fixed yet lmao

oh yeah XD, sorry.

**Pull request merged**
